<?php
declare(strict_types=1);

namespace Propcom\Accio;

class CliFormat
{
	const RESET_ALL = 0;
	const BOLD = 1;
	const DIM = 2;
	const UNDERLINE = 4;
	const BLINK = 5;
	const INVERT = 7;
	const HIDDEN = 8;
	const RESET_BOLD = 21;
	const RESET_DIM = 22;
	const RESET_UNDERLINE = 24;
	const RESET_BLINK = 25;
	const RESET_INVERT = 27;
	const RESET_HIDDEN = 28;
	const FOREGROUND_BLACK = 30;
	const FOREGROUND_RED = 31;
	const FOREGROUND_GREEN = 32;
	const FOREGROUND_YELLOW = 33;
	const FOREGROUND_BLUE = 34;
	const FOREGROUND_MAGENTA = 35;
	const FOREGROUND_CYAN = 36;
	const FOREGROUND_LIGHT_GREY = 37;
	const FOREGROUND_DEFAULT = 39;
	const BACKGROUND_BLACK = 40;
	const BACKGROUND_RED = 41;
	const BACKGROUND_GREEN = 42;
	const BACKGROUND_YELLOW = 43;
	const BACKGROUND_BLUE = 44;
	const BACKGROUND_MAGENTA = 45;
	const BACKGROUND_CYAN = 46;
	const BACKGROUND_LIGHT_GREY = 47;
	const BACKGROUND_DEFAULT = 49;
	const FOREGROUND_DARK_GREY = 90;
	const FOREGROUND_LIGHT_RED = 91;
	const FOREGROUND_LIGHT_GREEN = 92;
	const FOREGROUND_LIGHT_YELLOW = 93;
	const FOREGROUND_LIGHT_BLUE = 94;
	const FOREGROUND_LIGHT_MAGENTA = 95;
	const FOREGROUND_LIGHT_CYAN = 96;
	const FOREGROUND_LIGHT_WHITE = 97;
	const BACKGROUND_DARK_GREY = 100;
	const BACKGROUND_LIGHT_RED = 101;
	const BACKGROUND_LIGHT_GREEN = 102;
	const BACKGROUND_LIGHT_YELLOW = 103;
	const BACKGROUND_LIGHT_BLUE = 104;
	const BACKGROUND_LIGHT_MAGENTA = 105;
	const BACKGROUND_LIGHT_CYAN = 106;
	const BACKGROUND_LIGHT_WHITE = 107;
}
